const afrique = [
    "Afrique du Sud",
    "Angola",
    "Bénin",
    "Botswana",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cameroun",
    "Congo",
    "République démocratique du Congo",
    "Côte d'Ivoire",
    "Érythrée",
    "Ethiopie",
    "Gabon",
    "Gambie",
    "Ghana",
    "Guinée",
    "Guinée équatoriale",
    "Guinée-Bissau",
    "Kenya",
    "Lesotho",
    "Libéria",
    "Madagascar",
    "Malawi",
    "Mali",
    "Maurice",
    "Mozambique",
    "Namibie",
    "Niger",
    "Nigéria",
    "Ouganda",
    "République centrafricaine",
    "Rwanda",
    "Sao Tomé-et-Principe",
    "Sénégal",
    "Seychelles",
    "Sierra Leone",
    "Soudan du Sud",
    "Swaziland",
    "République-Unie de Tanzanie",
    "Tchad",
    "Togo",
    "Zambie",
    "Zimbabwe"
]

let amerique_latine_et_Caraibes = [
    "Antigua-et-Barbuda",
    "Argentine",
    "Bahamas",
    "Barbade",
    "Belize",
    "Etat plurinational de Bolivie ",
    "Brésil",
    "Chili",
    "Colombie",
     "Costa Rica",
     "Cuba",
     "Dominique",
     "El Salvador",
     "Equateur",
     "Grenade",
     "Guatemala",
     "Guyana",
     "Haïti",
     "Honduras",
     "Jamaïque",
     "Mexique",
     "Nicaragua",
     "Panama",
     "Paraguay",
     "Pérou",
     "République dominicaine",
     "Saint-Kitts-et-Nevis",
    "Saint-Vincent-et-les Grenadines",
    "Sainte-Lucie",
     "Suriname",
    "Trinité-et-Tobago",
   "Uruguay",
    "République bolivarienne du Venezuela "
]



let pays = [
    {"regionName": "afrique", "region":afrique},
    {"regionName": "Amerique latine et Caraibes", "region" :amerique_latine_et_Caraibes}
]
export default pays